# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd sss ldap
group:          files systemd sss ldap
shadow:         files systemd sss ldap
gshadow:        files systemd

hosts:          files mdns4_minimal [NOTFOUND=return] dns ldap
networks:       files ldap

protocols:      db files ldap
services:       db files sss ldap
ethers:         db files ldap
rpc:            db files ldap

netgroup:       nis sss ldap
automount:  sss
aliases:        ldap




